timeouts:
  llm_ms: 800
  asr_ms: 800
  tts_stop_ms: 300
cooldowns:
  greet_seconds: 300
queues:
  llm_max: 2
  vision_max: 50
circuit_breaker:
  llm:
    fail_threshold: 5
    cool_seconds: 60
retry:
  llm:
    max_attempts: 3
    base_backoff_ms: 200
priorities:
  alert: 10
  llm: 7
  wakeup: 5
  greet: 2